### ISSUE TITLE
No pom.xml or gradle files.

### ISSUE THREAD

**Issue by josephworks** [superblaubeere27/ClickGUI#1]
Plz add

**Comment by ghost** [comment]
or how about you be a normal person and stop using maven

**Comment by josephworks** [comment]
No, that doesn’t sound normal...
I would prefer at least a README.md on how to use it.

**Comment by superblaubeere27** [comment]
@josephworks I made a video about it https://www.youtube.com/watch?v=8VvoJgYr7hI&t=364s

**Comment by superblaubeere27** [comment]
@FinalPacket What is it suppose to be replaced with?

**Comment by josephworks** [comment]
Thanks for the vid!
